### ISSUE TITLE
Integrate HTML / CSS precompiler

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#46]
Pug, Sass, Less, Stylus ...

**Comment by scriptPilot** [comment]
For now, in my point of view there is no big benefit. Framework7-Vue is already streamlined to use for HTML, and CSS is mostly done already. So - keep it simple, use plain HTML and CSS I would say :-)

**Comment by lcaprini** [comment]
Hi @scriptPilot, first of all thank you for your awesome work.
In my opinion all style preprocessor, like Less, Sass, Pug, are very usefull, because a lot of app that I realize use a lot of custom components.
Using Sass (custom) functions, import, extends and variables would speed up my work, and also the style indentation make all code more readable.
my2cents :)
-L
