### ISSUE TITLE
Cordova platform installation failed for Android

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#489]
**Error message**
Adding android project...
Error: Error validating package name. Package name must look like: com.company.Name

Wrong playStoreId - Validation to be implemented.

**Comment by tassoman** [comment]
Hello there, I understand `npm run android` is forced launching an emulator previously set in AVD. 

I have no emulators because lack of RAM (in my system 4Gb isn't enough for studio+emu), is there any chance to run adb via usb on a phisical device?

I'm following documentation and is told to deploy to phone by `npm run studio` but it's trying to deploy to PlayStore and an ID is needed. I'm not yet registered (they ask 25$ also).

`npm run android`
```bash
BUILD SUCCESSFUL

Total time: 19.318 secs
Built the following apk(s): 
	/home/tassoman/devel/appframework/node_modules/cordova/bin/platforms/android/build/outputs/apk/android-debug.apk
ANDROID_HOME=/home/tassoman/Android/Sdk
JAVA_HOME=/usr/lib/jvm/java-8-oracle
Error: No emulator images (avds) found.
1. Download desired System Image by running: /home/tassoman/Android/Sdk/tools/android sdk
2. Create an AVD by running: /home/tassoman/Android/Sdk/tools/android avd
HINT: For a faster emulator, use an Intel System Image and install the HAXM device driver
```

`npm run studio` 
> Error: Cordova platform installation failed for Android.

Can we have a `npm run android-adb' command? Or something similar?
