### ISSUE TITLE
Images doesn't compile through v-bind

### ISSUE THREAD

**Issue by AndreyKomin** [scriptPilot/app-framework#640]
Images don't get inside the Cordova build if I use a variable inside SRC attr.
![image](https://user-images.githubusercontent.com/7191525/29163770-e6c87ce6-7dd6-11e7-80dc-66e55f7b1746.png)

**Comment by miner150000** [comment]
Not really a problem with the framework, it's because of how webpack manages compiling, when you specify the image location web pack compiles it and adds it to the compiled environment, but when you are assigning the image as a variable you would need to either import it before, or if it is absolutely random then you have to change the compilation not to use hashes on names (as you can see on the image you posted your compiled images are hashed) (or using hashes as queries) then calling the direct location as you did because web pack didn't know that you would be using than image and the path doesn't have the hash, if you need further information just tell me

**Comment by scriptPilot** [comment]
@AndreyKomin - You can work like this

```
... :src="image" ...


image = require('../path/to/image.png')
```
