### ISSUE TITLE
Run on android device with "cordova run android --device"

### ISSUE THREAD

**Issue by zevai** [scriptPilot/app-framework#726]
Hello!
App-framework is great job, thanks a lot! Very thoughtful documentation, i see for the first time something like this)
My suggestion is about testing application on android devices. In app-framework you provide "npm run studio" command, which loads Android Studio (actually I don't know what should be next step, because my AS installed in not usual path, so it was not launched). But I used another way for testing app on device, more lightweight I think.
I've just "cd .." to cordova bin (cordova project path) and used "cordova run android --device". It worked for me. I think it is totally command-line approach, which is not bad :-)
I suggest you to add some command like "npm run cordova" as alias to cordova command linked with cordova project path.
Also you may just add simple command "npm run android device" or somethink like this as alias for "cordova run android --device".
Thanks again for your project.

**Comment by fdbeirao** [comment]
The underlying problem is that `cordova emulate android` is [hardcoded](https://github.com/scriptPilot/app-framework/blob/master/scripts/cordova.js#L450-L453).

I changed that line in my `node_modules/app-framework/scripts/cordova.js` file to `cordova run android` and it now works fine. It does seem to build and launch the application twice for some reason 🤔.

**Comment by scriptPilot** [comment]
Thanks for this suggestion - beside the workaround, I will see how to improve.

**Comment by scriptPilot** [comment]
In upcoming V3, after each build Xcode and/or Android Studio open automatically ... just select the device/emulator and click on "Run" :-)
