### ISSUE TITLE
Ideas for App Framework 2

### ISSUE THREAD

**Issue by scriptPilot** [scriptPilot/app-framework#775]
Hello everybody,

App Framework 2 is in the pipe ... please find here the list of planned features:

https://github.com/scriptPilot/app-framework/blob/v2parcel/README.md

Feel free to add your ideas as an issue or as response to this thread :-)

Dennis

**Comment by tiptronic** [comment]
Hi Dennis,
thx for starting the work on v2!
But the link leads to 404!
andy

**Comment by moossun** [comment]
Excellent news

**Comment by josteph** [comment]
@scriptPilot The other day, I tried on using `phonegap-plugin-push` for Push notification implementation. I decided to use this because it's easier to implement than firebase. But it seems, even with fresh build, the plugin installation failed exactly at this plugin (even I tried to install this one without other plugin). Don't know what's the issue here, maybe can you try to reproduce ?

**Comment by tiptronic** [comment]
Is there anything going forward on v2?
To me, the most important thing would be the addition of Framework7-vue2, since structure of F7-pages changed quite a bit and there are many new / great additions to Vue2 lately.

Any info on this? (I already offered help & money 😉 )

andy

**Comment by mdonstad** [comment]
Is the focus of v2 going to be implementing framework7/vue v2 features? Would it safe to see we can work on v2 framework7 and then implement it into v2 when it is ready?

**Comment by mdonstad** [comment]
I understand your situation with your availability, but is there at least a preliminary timeline? I can also contribute a beer or two. ;)

**Comment by hoangld** [comment]
Support for Firebase Cloud Filestore would be great!

**Comment by ehausen** [comment]
Feature: Use custom Cordova (and other?) plugins. #788

**Comment by claudineisbezerra** [comment]
Hi Dennis,
Congrats for excellent work on v1.
I'm new for app-framework and just developed my first app using app-framework v1.
Since Framework7 v2 and Framework7 Vue v2 libraries had major and significant improvements I decided to migrate to the new versions.

Is there anything going forward on v2 in this sense that I should wait for?
What should be the best way to proceed with my updates regardless the timeline for the app-framework v2? Can I simply follow the instructions in 'Update vendor folder'?

Thanks in advance for evaluating these questions and for your help.

**Comment by scriptPilot** [comment]
Started to work on App Framework V3 - all your ideas are now part of single issues. Feel free to open new issues for your ideas.
